# Google Cloud Build script for Cloud Teleport

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - build
    - --tag=us-east5-docker.pkg.dev/internal-blockchain-indexed/dataflow-container/all-transfer-pipeline-template-container:latest
    - --file=./Dockerfile.all_transfer
    - .
images:
- 'us-east5-docker.pkg.dev/internal-blockchain-indexed/dataflow-container/all-transfer-pipeline-template-container:latest'